Support saving decode KV cache to boost multi-turn conversation
LMCache/LMCache pull request #149
Opened 2024-10-08 04:25 UTC by YaoJiayi

This PR resolves #129 .

Currently, decode cache is saved if seqlen (prompt tokens+generated tokens) % chunk_size == 0
By default, this feature is disabled.
To enable this feature, we need to specify "save_decode_cache: True" in config yaml. 
@Siddhant-Ray Please update the doc as well.

Currently, we only support mistral-7b.
There should be a patch per model. For example, in mistral-7b, assume the first run is text 1 -> text 2. Then input of the second run should take in text 1 + text 2. However, there's always an empty padding token 28705 between text 1 and text 2, making the cache for text 2 not reusable.
See

2024-10-08 05:13 UTC, KuntaiDu requested changes

2024-10-08 05:13 UTC, KuntaiDu commented on examples/save_decode_cache/offline_inference.py
> +#model_name = "meta-llama/Llama-3.1-8B-Instruct"
Maybe clean comments

2024-10-08 05:13 UTC, KuntaiDu commented on examples/save_decode_cache/offline_inference.py
> +        "content": "You are a helpgul assistant."
helpgul --> helpful

2024-10-08 05:13 UTC, KuntaiDu commented on examples/save_decode_cache/offline_inference.py
> +append_outputs(output_file, second_outputs, context_length, t4 - t3)
I feel like this file is a bit long -- but let's fix that later.

2024-10-08 09:37 UTC, ApostaC reviewed
Looks good to me! Please don't forget to let Siddhant update the documentation about the new configuration item.
Let's merge it after Kuntai approves

2024-10-10 03:57 UTC, KuntaiDu approved these changes
LGTM

2024-10-10 03:59 UTC, merged

2024-10-17 19:10 UTC, Shaoting-Feng commented
This has been E2E tested. **TTFT doesn't reduce; retrieved number of chunks looks good; `prompt_token_ids` confusing.** @YaoJiayi 
* E2E Test Setting
  * Suppose text1 is the prompt (context + question) of request 1 and text2 is the output message of request 1. Then text1 + text2 is the context of request 2. In this logic, I ran five-turn tests. The number of tokens goes from <100 to >15000.
* Performance: 
  * TTFT doesn't reduce
    |      | TTFT1 | TTFT2 | TTFT3 | TTFT4 | TTFT5 |
    |------|-------|-------|-------|-------|-------|
    | save_decode_cache: True  | 0.196 | 0.281 | 0.672 | 1.432 | 3.570 |
    | save_decode_cache: False | 0.094 | 0.558 | 0.684 | 1.529 | 3.769 |
  * From `stderr.log`, retrieved number of chunks: 
    * `save_decode_cache = True`: 0 0 2 10 25
    * `save_decode_cache = False`: 0 0 2 2 2
  * From `stdout.log`, last four IDs (after 28705) in `prompt_token_ids` are different in the next turn of request

2024-10-21 08:58 UTC, Shaoting-Feng commented
* About the number of retrieved chunks: 
  * Only the fifth round contain 15000 tokens. The fourth round contain 6538 tokens, so the test result of the number of retrieved chunks is correct.
* About the TTFT:
![Screen Shot 2024-10-21 at 03 57 18 AM](https://github.com/user-attachments/assets/5d0209d3-b668-44dc-b5a4-15c2601791b9)

2025-02-04 23:44 UTC, LifeIsHardBruh commented
> * About the number of retrieved chunks:
>   
>   * Only the fifth round contain 15000 tokens. The fourth round contain 6538 tokens, so the test result of the number of retrieved chunks is correct.
> * About the TTFT:
>   ![Screen Shot 2024-10-21 at 03 57 18 AM](https://private-user-images.githubusercontent.com/72972560/378347147-5d0209d3-b668-44dc-b5a4-15c2601791b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3MTE1MDQsIm5iZiI6MTczODcxMTIwNCwicGF0aCI6Ii83Mjk3MjU2MC8zNzgzNDcxNDctNWQwMjA5ZDMtYjY2OC00NGRjLWI1YTQtMTVjMjYwMTc5MWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA0VDIzMjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZWNjMGNkYmJhMjQwYzRkODA5NTE3N2JmYTQzYTFiZGVhYmYwMzRmMzVjN2JhODRhODQwMzcyMDdhN2E1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPWoOthfrrtX4ru4g_2KKdWdbyasK9x82GLpILR6Xug)

Hi, I have a question regarding this E2E test: I am wondering why the TTFTs without LMCache are lower than the TTFTs with LMCache in later turns. Isn't reusing KV caches going to reduce the context-processing delay and TTFTs?

2025-02-04 23:47 UTC, ApostaC commented
@LifeIsHardBruh Hey, the above figure is extremely outdated. Current lmcache performance should not be worse than no-lmcache