Add Disk Manager
LMCache/LMCache pull request #224
Opened 2024-11-13 19:47 UTC by qyy2003

Add local disk manager to manage all the LMCache processes' disk read and write. Centralize the KV Cache dict and evictor.

**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**

---

<details>

<summary><b> PR Checklist (Click to Expand) </b></summary>

<p>Thank you for your contribution to LMCache! Before submitting the pull request, please ensure the PR meets the following criteria. This helps us maintain the code quality and improve the efficiency of the review process.</p>

<h3>PR Title and Classification</h3>
<p>Please try to classify PRs for easy understanding of the type of changes. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
    <li><code>[Bugfix]</code> for bug fixes.</li>
    <li><code>[CI/Build]</code> for build or continuous integration improvements.</li>
    <li><code>[Doc]</code> for documentation fixes and improvements.</li>
    <li><code>[Model]</code> for adding a new model or improving an existing model. Model name should appear in the title.</li>
    <li><code>[Core]</code> for changes in the core LMCache logic (e.g., <code>LMCacheEngine</code>, <code>Backend</code> etc.)</li>
    <li><code>[Misc]</code> for PRs that do not fit the above categories. Please use this sparingly.</li>
</ul>
<p><strong>Note:</strong> If the PR spans more than one category, please include all relevant prefixes.</p>

<h3>Code Quality</h3>

<p>The PR need to meet the following code quality standards:</p>

<ul>
    <li>Pass all linter checks. Please use <a href="https://github.com/LMCache/LMCache/blob/dev/format.sh"><code>format.sh</code></a> to format your code.</li>
    <li>The code need to be well-documented to ensure future contributors can easily understand the code.</li>
    <li> Please include sufficient tests to ensure the change is stay correct and robust. This includes both unit tests and integration tests.</li>
</ul>

<h3>What to Expect for the Reviews</h3>

We aim to address all PRs in a timely manner. If no one reviews your PR within 5 days, please @-mention one of KuntaiDu, ApostaC or YaoJiayi.

2024-12-03 20:20 UTC, YaoJiayi requested changes
Thanks @qyy2003 ! I left some comments. Btw, could you add some benchmark numbers (with e2e test in lmcache-tests)?

2024-12-03 20:20 UTC, YaoJiayi commented on examples/disk_backend/keymanager.yaml
> +disk_path: "/dataheart/qinyuyang2003/local_disk/"
Can we reuse the original disk url format?

2024-12-03 20:20 UTC, YaoJiayi commented on examples/disk_backend/keymanager.yaml
> +serde: None
These `fmt`, `dtype` and `chunk_size` variables should be configured from vllm instead of hardcoded here.

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/abstract_backend.py
> +
What's the difference between this interface and the LMCBackendInterface?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +        self.remote_serde = Info["serde"]
These should be passed in from vllm metadata.

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +            )  # This will raise an exception if the Future failed.
When does it fail?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +            self.update_lock.acquire()
What is the need for this lock here?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +    def put_worker(self, ):
When is put_worker used?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +    def batched_put_worker(self, ):
Why are we coupling the `proxy.batched_put` and the actual put?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +            self.cpu_mbufferpool.idx_free(chunk_idx)
We can use lambda callbacks to free the memory object without modifying the memory buffer.

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +            self.cpu_mbufferpool.idx_free(chunk_idx)
Plus, it doesn't look thread_safe here:)

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +            time.sleep(0.1)
Maybe I'm wrong. But isn't this gonna degrade the performance (even taking more time than recomputation) in certain scenarios (e.g., lots of writes happening)?

2024-12-03 20:20 UTC, YaoJiayi commented on examples/disk_backend/keymanager.yaml
> +serde: None
Also, I feel it's better to initialize the disk manager in lmcache-vllm.

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_keymanager.py
> +    def put(self, key_str: str, kv_size: float, status: bool) -> str:
When is this `put` function used?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_keymanager.py
> +    def get(
Same here. Is `get` ever used anywhere?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_keymanager.py
> +        print("BATCHED_GET")
Remove the prints. Use logger instead.

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_keymanager.py
> +    # start_server(LMCKeyManagerConfig.from_file(config_path))
Remove useless comments

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/serde/__init__.py
> +    print(metadata.kv_dtype)
Please remove all the prints

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/utils.py
> +STR_DTYPE_TO_TORCH_DTYPE = {
When is this ever used?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/storage_backend/disk_backend.py
> +            time.sleep(0.1)
Also, use enum to indicate diiferent status. Numbers are confusing.

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/utils.py
> +    model_name: str
How is different from `CacheEngineKey`?

2024-12-03 20:20 UTC, YaoJiayi commented on lmcache/utils.py
> +class CacheBackendInfo:
Seems to be overlapping to other config and metadata?

2024-12-04 15:47 UTC, qyy2003 commented
Consider two scenarios:  
1. A V100 instance and an A100 instance share a common KV Cache in `float16` and `bfloat16` formats. Should this KV Cache be shared between them?  
2. Suppose a machine has two disk directories available for KV Cache storage, such as `/local/local_disk` and `/dataheart/local_disk`. Who should determine where the KV Cache is stored—the global manager or the backend within the LLM engine itself?  

To address these challenges, I propose a **global manager** that oversees the storage and retrieval of KV Cache. This manager would determine:  
- Which machine, disk directory, and data type (`dtype`) should be used for KV Cache storage and retrieval.  
- Which KV Cache should be evicted when needed.  

The global manager should function as an **address manager**, implemented in two distinct roles:  
- **Disk Path Manager**: Oversees the organization and management of storage paths for KV Cache on local or shared disks.  
- **Distributed Router Manager**: Handles routing and coordination for KV Cache storage across distributed storage servers using URLs.  

### Core Functions of the Address Manager:  

1. **`contains(key)`**: Checks if a specific key exists and returns the associated address (as a string). If the key does not exist, it returns an empty string.  
2. **`write_end(key)`**: Signals the address manager that the specified key is ready to be read.  
3. **`read_ready(key)`**: Retrieves the address (as a string) for the specified key. Returns an empty string if the key does not exist or is not ready for reading.  
4. **`remove(key)`**: Evicts the specified key globally.

2024-12-05 18:46 UTC, closed without merging